name: Create New Release Note

on:
  push:
    branches:
      - master
    paths:
      - '_data/latest/**'

jobs:
  apidoc-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.TEST}}

    steps:    
    - name: Install jq for json manipulation
      run: sudo apt-get install jq

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create new release note
      run: |
        VERSION="`jq -r '.version' _data/latest/metadata.json`"
        mkdir downloads/release-notes/$VERSION
        cp downloads/RELEASE_NOTE.md downloads/release-notes/$VERSION

    - name: Push changes for new API Docs
      run: |
        git checkout automate-release-$GITHUB_SHA 2>/dev/null || git checkout -b automate-release-$GITHUB_SHA
        git pull origin master
        
        git config --global user.email "ballerina-bot@ballerina.org"
        git config --global user.name "shafreenAnfar"
        
        VERSION="`jq -r '.version' _data/latest/metadata.json`"
        git add downloads/release-notes/$VERSION
        git commit --allow-empty -m 'Update API Docs'
        
        git push --set-upstream origin automate-release-$GITHUB_SHA
        echo 'Successfully pushed to automate-release-$GITHUB_SHA branch'

    - name: Create pull request for new BBEs
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -m '[Automated] Create release note folder for the new release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}