name: Update release notes json of ballerina.io

on:
  push:
    branches:
      - master

jobs:
  Update:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.TEST}}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
   
    - name: Cloning ballerina-release
      run: git clone https://shafreenAnfar:$GITHUB_TOKEN@github.com/shafreenAnfar/ballerina-release.git

    - name: Generate the new release-notes-json file
      run: python3 ballerina-release/publish_scripts/publish_json.py _data/release_notes_versions.json _data/metadata.json

    - name: Copy newly generated release-notes-json file
      run: cp ballerina-release/publish_scripts/target/output/release_notes_versions.json _data/release_notes_versions.json

    - name: Updating release-notes-versions json file
      run: |
        git checkout automate-release-notes-json 2>/dev/null || git checkout -b automate-release-notes-json
        git pull origin master
        
        git config --global user.email "www.call911@gmai.com"
        git config --global user.name "shafreenAnfar"
        git add _data/release_notes_versions.json
        git commit --allow-empty -m 'Release notes json update'
        
        git push --set-upstream origin automate-release-notes-json
        echo 'Successfully pushed to automate-downloads-page-update branch'
        sudo snap install hub --classic
        hub pull-request -m 'This is an automated pull request to update release_notes_versions.json for new release'
