name: Generate ballerina by examples

on:
  push:
    branches:
      - master
    paths:
    - '_data/**'

jobs:
  bbe-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.TEST}}

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.6.2
      env:
        GOPATH: /home/runner/work/ballerina-release

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cloning ballerina-release
      run: git clone https://shafreenAnfar:$GITHUB_TOKEN@github.com/ballerina-platform/ballerina-release.git

    - name: Install json parser
      run: sudo apt install jq

    - name: Generate BBEs
      run: |
        cd ballerina-release
        ./ballerinaByExample/build-bbe.sh _data/metadata.json

    - name: Set relevant folder as env variable 
      run: |
	site_folder="`jq -r '.version' _data/metadata.json`"
	array=($(echo $site_folder | tr "." "\n"))
  	SITE_FOLDER="${array[0]}.${array[1]}"
	export SITE_FOLDER=$SITE_FOLDER

    - name: Remove old examples file
      run: git rm -r ${SITE_FOLDER}/learn/by-example

    - name: Copy newly generated examples file
      run: cp -r by-example ${SITE_FOLDER}/learn/

    - name: Updating by examples file
      run: |
        git checkout automate-bbes-$GITHUB_SHA 2>/dev/null || git checkout -b automate-bbes-$GITHUB_SHA
        git pull origin master
        
        git config --global user.email "ballerina-bot@ballerina.org"
        git config --global user.name "shafreenAnfar"
        git add ${SITE_FOLDER}/learn/by-example
        git commit --allow-empty -m 'Update release notes json'
        
        git push --set-upstream origin automate-release-notes-json-$GITHUB_SHA
        echo 'Successfully pushed to automate-downloads-page-update branch'
        sudo snap install hub --classic
        hub pull-request -m '[Automated] Update Ballerina by examples(BBEs) for new release'
